### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by Dominiclemus** [ds4owd-001/md-02-assignments-Dominiclemus#1]
@larnsce 
@mianzg 
@sskorik01 
I do not understand the whole "issue" thing in Github. Like what do we be doing when we create a new issue?

**Comment by sskorik01** [comment]
Congratulations on completing and pushing your second assignment! 

When you create a new issue, you are essentially creating a new task or bug report that needs to be addressed. By tagging us, it allows us to have a look at your problem/questions as well as your code (when you complete your assignment for example). Once the issue/task is resolved, it can be closed. So you can close this issue now 💯
